%YAML 1.2

#General Component Desciption
component : "Cream-CE"
version : 2.7
docker_hub_url : ""
puppet_forge_url: ""
#Configration Metadata
site-info:
    name:
        type: string
        description: 'name of the site'
    email: 
        type: string
        description: 'email address for point of contact'
    security_email:
        type: string
        description: ''
    support_email:
        type:
        description: ''
    latitude:
        type: string
        description: ''
    longitude: double
        type: string
        desciption: ''
    description:
        type: double
        description: ''
    location:
        type: string
        description: ''
    website:
        type: url
        description: '' 
    other_grid:
        type: url
        description: ''
ce-info:
    name:     
